"""Render the digest email — HTML with inline styles only (Gmail strips <style>)
plus a plain-text alternative part.
"""

from __future__ import annotations

import html as html_mod
from datetime import datetime

# Colors shared by badge/chip rendering.
_GREEN, _AMBER, _RED, _MUTED = "#1a7f37", "#9a6700", "#cf222e", "#57606a"


def _esc(text: str | None) -> str:
    return html_mod.escape(text or "")


def _score_badge(score: int) -> str:
    color = _GREEN if score >= 70 else _AMBER
    return (f'<span style="background:{color};color:#ffffff;border-radius:4px;'
            f'padding:2px 7px;font-size:13px;font-weight:bold">{score}</span>')


def _chips(items: list[str], color: str) -> str:
    if not items:
        return ""
    chips = "".join(
        f'<span style="display:inline-block;background:{color}1a;color:{color};'
        f'border:1px solid {color}55;border-radius:10px;padding:0 8px;'
        f'font-size:12px;margin:2px 4px 2px 0">{_esc(i)}</span>'
        for i in items
    )
    return chips


def _job_html(e: dict) -> str:
    meta_bits = [b for b in (
        _esc(e["company"]), _esc(e["location"]), _esc(e["posted_text"]), _esc(e["salary"]),
    ) if b]
    meta = " — ".join(meta_bits)
    missing = ""
    if e["missing_must_haves"]:
        missing = (
            '<div style="color:{};font-size:12px;margin:3px 0">Missing must-have: {}</div>'
            .format(_RED, _esc(", ".join(e["missing_must_haves"])))
        )
    resume = ""
    if e["recommended_resume"]:
        resume = (
            '<span style="color:{};font-size:12px">Recommended resume: <b>{}</b></span>'
            .format(_MUTED, _esc(e["recommended_resume"]))
        )
    return f"""
<div style="border:1px solid #d0d7de;border-radius:8px;padding:10px 14px;margin:10px 0;font-family:Segoe UI,Arial,sans-serif">
  <div style="font-size:15px;margin-bottom:3px">{_score_badge(e['score'])}
    <a href="{_esc(e['url'])}" style="color:#0969da;text-decoration:none;font-weight:600">{_esc(e['title'])}</a>
  </div>
  <div style="color:{_MUTED};font-size:13px;margin-bottom:4px">{meta}</div>
  <div>{_chips(e['matched_skills'], _GREEN)}{resume}</div>
  {missing}
</div>"""


def render_html(entries: list[dict], stats: dict) -> str:
    now = datetime.now().strftime("%d %b %H:%M")
    header = (
        f"{stats.get('jobs_seen', 0)} seen · {stats.get('new_jobs', 0)} new · "
        f"{stats.get('reposts', 0)} reposts skipped · {stats.get('stale', 0)} too old · "
        f"{stats.get('excluded', 0)} excluded · {stats.get('details_fetched', 0)} JDs fetched"
    )
    errors = ""
    if stats.get("errors"):
        items = "".join(f"<li>{_esc(e)}</li>" for e in stats["errors"])
        errors = f'<div style="color:{_RED};font-size:12px;margin:6px 0"><b>Failures this run:</b><ul>{items}</ul></div>'
    jobs = "".join(_job_html(e) for e in entries)
    return f"""\
<div style="font-family:Segoe UI,Arial,sans-serif;max-width:680px">
  <div style="font-size:18px;font-weight:bold;color:#1f2328">Job Radar — {now}</div>
  <div style="color:{_MUTED};font-size:13px;margin:4px 0 8px">{header}</div>
  {errors}
  {jobs}
  <div style="color:{_MUTED};font-size:11px;margin-top:14px;border-top:1px solid #d0d7de;padding-top:8px">
    Generated by Job Radar · scores are keyword-match percentages, not a promise.
  </div>
</div>"""


def _job_text(e: dict) -> str:
    meta_bits = [b for b in (e["company"], e["location"], e["posted_text"], e["salary"]) if b]
    lines = [
        f"[{e['score']}] {e['title']}" + (f" — {' — '.join(meta_bits)}" if meta_bits else ""),
        f"      Matched: {', '.join(e['matched_skills']) or '—'}"
        + (f" | Missing must-have: {', '.join(e['missing_must_haves'])}" if e["missing_must_haves"] else ""),
    ]
    if e["recommended_resume"]:
        lines.append(f"      Recommended resume: {e['recommended_resume']}")
    lines.append(f"      Apply: {e['url']}")
    return "\n".join(lines)


def render_text(entries: list[dict], stats: dict) -> str:
    now = datetime.now().strftime("%d %b %H:%M")
    head = (
        f"Job Radar — {now}\n"
        f"{stats.get('jobs_seen', 0)} seen · {stats.get('new_jobs', 0)} new · "
        f"{stats.get('reposts', 0)} reposts skipped · {stats.get('excluded', 0)} excluded\n"
    )
    if stats.get("errors"):
        head += "Failures this run:\n" + "".join(f"  - {e}\n" for e in stats["errors"])
    body = "\n\n".join(_job_text(e) for e in entries)
    return head + "\n" + body + "\n"
